begin;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name varchar(100) not null check (char_length(trim(name)) > 0),
  rating smallint not null check (rating between 1 and 5),
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists reviews_created_at_idx on public.reviews(created_at desc);
alter table public.reviews enable row level security;

commit;
