begin;

create table if not exists public.college_students (
  id bigint generated by default as identity primary key,
  source_id integer unique,
  full_name varchar(200) not null,
  display_name varchar(150),
  name_arabic varchar(200),
  place varchar(100),
  admission_no varchar(50),
  class_id integer,
  maddhab_id integer,
  phone varchar(30),
  email varchar(150),
  dob date,
  guardian_name varchar(200),
  guardian_phone varchar(30),
  status varchar(16) not null default 'active' check (status in ('active','graduated','left','inactive')),
  chess_number varchar(50) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists college_students_name_idx on public.college_students(lower(full_name));
create index if not exists college_students_class_idx on public.college_students(class_id,status);
alter table public.college_students enable row level security;

commit;
