begin;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug in ('green','white','blue','yellow')),
  name text not null,
  score numeric(8,2) not null default 0 check (score >= 0),
  color varchar(9) not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  session text not null check (session in ('subahi','morning','afternoon','evening','night')),
  start_time time not null,
  duration_minutes integer not null check (duration_minutes > 0),
  venue text not null default 'Main Auditorium',
  status text not null default 'upcoming' check (status in ('upcoming','live','completed')),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  team_id bigint not null references public.teams(id) on delete restrict,
  program_id bigint references public.programs(id) on delete set null,
  category text not null,
  reporting_time time not null,
  created_at timestamptz not null default now()
);

create table if not exists public.college_students (
  id bigint generated by default as identity primary key,
  source_id integer unique,
  full_name varchar(200) not null,
  display_name varchar(150),
  name_arabic varchar(200),
  place varchar(100),
  admission_no varchar(50),
  class_id integer,
  maddhab_id integer,
  phone varchar(30),
  email varchar(150),
  dob date,
  guardian_name varchar(200),
  guardian_phone varchar(30),
  status varchar(16) not null default 'active' check (status in ('active','graduated','left','inactive')),
  chess_number varchar(50) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  participant_id bigint not null references public.participants(id) on delete cascade,
  score numeric(5,2) not null check (score between 0 and 100),
  position integer not null check (position > 0),
  is_published boolean not null default false,
  published_at timestamptz,
  unique(program_id, participant_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name varchar(100) not null check (char_length(trim(name)) > 0),
  rating smallint not null check (rating between 1 and 5),
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id smallint primary key default 1 check (id = 1),
  festival_name varchar(120) not null default 'Kauzariyya Arts Festival 2026',
  festival_date date not null default '2026-07-05',
  intro_video_enabled boolean not null default true,
  intro_video_url varchar(500) not null default 'assets/intro.mp4',
  intro_video_loop boolean not null default false,
  video_darkness smallint not null default 38 check (video_darkness between 0 and 75),
  animations_enabled boolean not null default true,
  scoreboard_live boolean not null default true,
  schedule_blocks jsonb not null default '[{"key":"subahi","label":"Subahi","start_time":"05:00","end_time":"07:00"},{"key":"morning","label":"Morning","start_time":"09:00","end_time":"12:45"},{"key":"afternoon","label":"Afternoon","start_time":"14:30","end_time":"16:30"},{"key":"evening","label":"Evening","start_time":"19:30","end_time":"20:45"},{"key":"night","label":"Night","start_time":"21:30","end_time":"23:00"}]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

create index if not exists programs_start_time_idx on public.programs(start_time);
create index if not exists participants_name_idx on public.participants(lower(name));
create index if not exists college_students_name_idx on public.college_students(lower(full_name));
create index if not exists college_students_class_idx on public.college_students(class_id,status);
create index if not exists results_published_idx on public.results(is_published, published_at desc);
create index if not exists reviews_created_at_idx on public.reviews(created_at desc);

alter table public.teams enable row level security;
alter table public.programs enable row level security;
alter table public.participants enable row level security;
alter table public.college_students enable row level security;
alter table public.results enable row level security;
alter table public.reviews enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "Public read teams" on public.teams;
create policy "Public read teams" on public.teams for select using (true);
drop policy if exists "Public read programs" on public.programs;
create policy "Public read programs" on public.programs for select using (true);
drop policy if exists "Public read participants" on public.participants;
create policy "Public read participants" on public.participants for select using (true);
drop policy if exists "Public read published results" on public.results;
create policy "Public read published results" on public.results for select using (is_published = true);
drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings" on public.site_settings for select using (true);

commit;
