begin;

INSERT INTO public.college_students (source_id,full_name,display_name,name_arabic,place,admission_no,class_id,maddhab_id,phone,email,dob,guardian_name,guardian_phone,status,chess_number) VALUES
(1,'Hudaifa','Hudaifa kottayam','حذيفة','Ettumanoor',NULL,4,1,'9037861024',NULL,NULL,NULL,NULL,'active','KZ-001'),
(2,'Rashad','Rashad TVM','رشاد','TVM',NULL,4,2,'94963 92425',NULL,NULL,NULL,NULL,'active','KZ-002'),
(3,'Aadam','Aadam','آدم','TVM',NULL,4,2,'97461 87288',NULL,NULL,NULL,NULL,'active','KZ-003'),
(4,'Salman','Salman TVM','سلمان','TVM',NULL,4,2,'96336 79003',NULL,NULL,NULL,NULL,'active','KZ-004'),
(5,'Mahin Sha','Mahin Sha','ماح شاه','Muvattupuzha',NULL,4,1,'89431 40844',NULL,NULL,NULL,NULL,'active','KZ-005'),
(6,'Haroon','Haroon','هارون','Thookupalam',NULL,4,1,'8075 489 927',NULL,NULL,NULL,NULL,'active','KZ-006'),
(7,'Shaad','Shaad','شاد','Kasaragod',NULL,4,2,'6282 476 461',NULL,NULL,NULL,NULL,'active','KZ-007'),
(8,'Anfaal','Anfal','أنفال','Thodupuzha',NULL,4,1,'73065 28443',NULL,NULL,NULL,NULL,'active','KZ-008'),
(9,'Asjad Rahman','Asjad Rahman','أسجد','Kuthiravettam',NULL,4,1,'755 996 4183',NULL,NULL,NULL,NULL,'active','KZ-009'),
(10,'Hamzath Ali','Hamzath Ali','حمزة علي','Vazhakkulam',NULL,4,2,'94953 55300',NULL,NULL,NULL,NULL,'active','KZ-010'),
(11,'Shahul','Shahul','شاهل','Muvattupuzha',NULL,4,1,'97781 68543',NULL,NULL,NULL,NULL,'active','KZ-011'),
(12,'Swalih','Swalih','صالح','Thodupuzha',NULL,4,1,'6282 136 908',NULL,NULL,NULL,NULL,'active','KZ-012'),
(13,'Muhsin','Muhsin Edathala',NULL,'Edathala',NULL,2,1,'92078 66709',NULL,NULL,NULL,NULL,'active','KZ-013'),
(14,'Farhan','Farhan',NULL,'Kumali',NULL,2,1,'73065 61146',NULL,NULL,NULL,NULL,'active','KZ-014'),
(15,'Ahsan','Ahsan',NULL,'Kanjar',NULL,2,1,'94473 43885',NULL,NULL,NULL,NULL,'active','KZ-015'),
(16,'Abdulla Jaleel','Abdulla Jaleel',NULL,'Muvattupuzha',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-016'),
(17,'Safwan','Safwan Chilav',NULL,'Chilavu',NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-017'),
(18,'Faiz','Faiz Erpt','فائز','Erattupeta',NULL,3,1,'97446 41826',NULL,NULL,NULL,NULL,'active','KZ-018'),
(19,'Adheeb','Adheeb','أديب','Palakkad',NULL,3,1,'97782 23825',NULL,NULL,NULL,NULL,'active','KZ-019'),
(20,'Amanulla','Amanulla','أمان الله','Pallikkara',NULL,3,2,'98473 09667',NULL,NULL,NULL,NULL,'active','KZ-020'),
(21,'Ameen','Ameen Edathala','أمين','Edathala',NULL,3,1,'90373 80923',NULL,NULL,NULL,NULL,'active','KZ-021'),
(22,'In''am','In''am kanjar','إنعام','kanjar',NULL,3,1,'6282 342 864',NULL,NULL,NULL,NULL,'active','KZ-022'),
(23,'Abrar','Abrar','أبرار','Kanjar',NULL,3,NULL,'80757 51552',NULL,NULL,NULL,NULL,'active','KZ-023'),
(24,'Fardheen','Fardheen','فردين','thodupuzha',NULL,3,1,'755 998 4689',NULL,NULL,NULL,NULL,'active','KZ-024'),
(25,'Sufyan','Sufyan Edathala','سفيان','Edathala',NULL,3,2,'97469 38733',NULL,NULL,NULL,NULL,'active','KZ-025'),
(26,'In''am','In''am MVPT','إنعام','Muvattupuzha',NULL,3,2,'73562 46129',NULL,NULL,NULL,NULL,'active','KZ-026'),
(27,'Yaseen','Yaseen P','يس','Pallarimankalam',NULL,3,2,'81118 10739',NULL,NULL,NULL,NULL,'active','KZ-027'),
(28,'Yaseen','Yaseen Edathala','يس','Edathala',NULL,3,2,'9744706410',NULL,NULL,NULL,NULL,'active','KZ-028'),
(29,'Yaseen','Yaseen K','يس','Kottarakkara',NULL,3,NULL,'96336 25682',NULL,NULL,NULL,NULL,'active','KZ-029'),
(30,'Yaseen','Yaseen TDP','يس','Thodupuzha',NULL,3,2,'9037081248',NULL,NULL,NULL,NULL,'active','KZ-030'),
(31,'Hafis','Hafis Kodungallur','حافظ','Kodungallur',NULL,3,2,'98952 68422',NULL,NULL,NULL,NULL,'active','KZ-031'),
(32,'Ahamed','Ahamed','أحمد','Kollam',NULL,3,2,'94000 38616',NULL,NULL,NULL,NULL,'active','KZ-032'),
(34,'Ashik','Ashik Thookupalam','عاشق','Thookupalam',NULL,3,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-034'),
(35,'Muzzammil','Muzzammil Navas','مزمل','Thodupuzha',NULL,3,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-035'),
(36,'Zaid Ali','Zaid ali','زيد علي','vennala',NULL,3,NULL,'97784 66618',NULL,NULL,NULL,NULL,'active','KZ-036'),
(37,'Badusha','Badusha','باد شاه','Kothamangalam',NULL,4,NULL,'85904 17029',NULL,NULL,NULL,NULL,'active','KZ-037'),
(38,'Mezin','Mezin',NULL,'Kannur',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-038'),
(39,'Akmal','Akmal','أكمل','Maysore',NULL,3,2,'88672 90521',NULL,NULL,NULL,NULL,'active','KZ-039'),
(40,'Badrudheen','Badarudheen','بدر الدين','Pallarimankalam',NULL,3,2,'79079 82301',NULL,NULL,NULL,NULL,'active','KZ-040'),
(41,'Abdulla','Abdulla PKD',NULL,'Palakkad',NULL,5,1,'81390 29440',NULL,NULL,NULL,NULL,'active','KZ-041'),
(42,'Habeebulla','Habeebulla',NULL,'Palakkad',NULL,5,1,'95675 92130',NULL,NULL,NULL,NULL,'active','KZ-042'),
(43,'Ziyad Ali','Ziyad Ali',NULL,'Edappalli',NULL,5,2,'79947 13109',NULL,NULL,NULL,NULL,'active','KZ-043'),
(44,'Abid','Abid Vannappuram',NULL,'Vannapauram',NULL,2,2,'96565 09266',NULL,NULL,NULL,NULL,'active','KZ-044'),
(45,'Anzil','Anzil',NULL,'Perumbavoor',NULL,5,2,'77369 81393',NULL,NULL,NULL,NULL,'active','KZ-045'),
(46,'Muhammed','Muhammed Thrissoor',NULL,'Thrishoor',NULL,5,2,'70257 95579',NULL,NULL,NULL,NULL,'active','KZ-046'),
(47,'Abdul rahman','Abdul Rahman PKD',NULL,'Palakkad',NULL,5,1,'80503 61161',NULL,NULL,NULL,NULL,'active','KZ-047'),
(48,'Arshad Rahman','Arshad Rahman',NULL,'Kollam',NULL,5,1,'99958 61100',NULL,NULL,NULL,NULL,'active','KZ-048'),
(49,'Ayan Rahman','Ayan Rahman',NULL,'aluva',NULL,5,2,'62381 47499',NULL,NULL,NULL,NULL,'active','KZ-049'),
(50,'Sawad','Sawad',NULL,'Thodupuzha',NULL,5,1,'83018 08847',NULL,NULL,NULL,NULL,'active','KZ-050'),
(51,'Salim','Salim',NULL,'Pukkattupadi',NULL,5,2,'97468 48819',NULL,NULL,NULL,NULL,'active','KZ-051'),
(52,'Riyas','Riyas',NULL,'Kodungalloor',NULL,5,2,'81138 35564',NULL,NULL,NULL,NULL,'active','KZ-052'),
(53,'Mihran','Mihran',NULL,'Aluva',NULL,5,NULL,'8075 145 559',NULL,NULL,NULL,NULL,'active','KZ-053'),
(54,'Miras','Miras',NULL,'Kasaragod',NULL,5,NULL,'90375 30747',NULL,NULL,NULL,NULL,'active','KZ-054'),
(55,'Mahin','Mahin MVPT',NULL,'Muvattupuzha',NULL,5,1,'95391 92540',NULL,NULL,NULL,NULL,'active','KZ-055'),
(56,'Nasrulla','Nasrulla',NULL,'Thodupuzha',NULL,5,2,'90746 13604',NULL,NULL,NULL,NULL,'active','KZ-056'),
(57,'Saeed','Saeed Aluva',NULL,'Aluva',NULL,5,2,'97784 44164',NULL,NULL,NULL,NULL,'active','KZ-057'),
(58,'Anas','Anas Pukkattupadi',NULL,'Pukkattupadi',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-058'),
(59,'Abdul Azeez','Abdul Azeez',NULL,'Pathanapuram',NULL,6,1,'89430 76486',NULL,NULL,NULL,NULL,'active','KZ-059'),
(60,'Abdulla Kunjumon','Abdulla Kunjumon',NULL,'Aluva',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-060'),
(61,'Hafiz Hassan','Hafiz Hassan',NULL,'Pattimattam',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-061'),
(62,'Abdu Rahman','Abdu Rahman Vazhakkulam',NULL,'Vazhakkulam',NULL,6,2,'7012038305',NULL,NULL,NULL,NULL,'active','KZ-062'),
(63,'Imran','Imran',NULL,'Kasaragod',NULL,6,2,'75106 18313',NULL,NULL,NULL,NULL,'active','KZ-063'),
(64,'Noufal','Noufal Raziq',NULL,'Kannur',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-064'),
(65,'Salman','Salman Ibrahim',NULL,'Chilav',NULL,6,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-065'),
(66,'Swalih','Swalih TDPA',NULL,'Thodupuzha',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-066'),
(67,'Ahmed Yaseen','Ahmed Yaseen',NULL,'Edathala',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-067'),
(68,'Yaseen','Yaseen kanjar',NULL,'kanjar',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-068'),
(69,'Usama','Usama',NULL,'Pattimattam',NULL,5,1,'88917 46695',NULL,NULL,NULL,NULL,'active','KZ-069'),
(70,'Hassan','Hassan',NULL,'Kozhikkod',NULL,5,2,'95944 90977',NULL,NULL,NULL,NULL,'active','KZ-070'),
(71,'Hussain','Hussain',NULL,'Kozhikkod',NULL,5,2,'95944 90977',NULL,NULL,NULL,NULL,'active','KZ-071'),
(72,'Muzzammil','Muzzammil TDPA',NULL,'Thodupuzha',NULL,5,1,'80893 68995',NULL,NULL,NULL,NULL,'active','KZ-072'),
(73,'Swalih','Swalih basheer',NULL,'Paravoor',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-073'),
(74,'Rizwan','Rizwan',NULL,'Thodupuzha',NULL,6,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-074'),
(75,'Adhil','Adhil Pattimattam','علدل','Pattimattam',NULL,3,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-075'),
(76,'Shuraim','Shuraim',NULL,'Kasaragod',NULL,2,NULL,'88488 67392',NULL,NULL,NULL,NULL,'active','KZ-076'),
(77,'Favas','Favas',NULL,'Kollam',NULL,5,2,'62829 98572',NULL,NULL,NULL,NULL,'active','KZ-077'),
(79,'Ammar','Ammar','عملر','Malippuram',NULL,4,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-079'),
(80,'Naseef','Naseef',NULL,'Perumbavoor',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-080'),
(81,'As''adh','As''adh',NULL,'Nedungandam',NULL,6,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-081'),
(82,'Ashkar','Ashkar','أشكر','kollam',NULL,4,2,'8289806296',NULL,NULL,NULL,NULL,'active','KZ-082'),
(83,'Abdulla','Abdulla Pdl','عبد الله','Pandalam',NULL,4,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-083'),
(84,'Thoyyib','Thoyyib','طيب','Edathala',NULL,4,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-084'),
(85,'Abdulla','Abdullah Edathala',NULL,'Edathala',NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-085'),
(87,'Saeed','Saeed Kottayam',NULL,'Kottayam',NULL,10,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-087'),
(88,'Yasir','Yasir',NULL,'Thrissur',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-088'),
(89,'Abdulla Anas','Abdulla Anas',NULL,'Perumbavoor',NULL,6,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-089'),
(90,'Ashiq Basheer','Ashiq Basheer',NULL,'Muvattupuzha',NULL,3,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-090'),
(91,'Arshaq','Arshaq',NULL,'Kasaragod',NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-091'),
(92,'Abid','Abid Manjappetti',NULL,'Manjappetti',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-092'),
(93,'Mahmood Hasan','Mahmood Hasan',NULL,'Kodungalloor',NULL,3,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-093'),
(94,'Haneef','Haneef',NULL,'Thodupuzha',NULL,3,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-094'),
(95,'Ishaq','Ishaq',NULL,'Erattupeta',NULL,3,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-095'),
(96,'Abdul Basith','Abdul Basith',NULL,'Parakkode',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-096'),
(97,'Aman Zaki','Aman Zaki',NULL,'Kannur',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-097'),
(98,'Umarul Farooq','Umarul Farooq',NULL,'Kodungalloor',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-098'),
(99,'Maqbool','Maqbool',NULL,'Vedimara',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-099'),
(100,'Mis''ab','Mis''ab',NULL,'Kochi',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-100'),
(101,'Haroon','Haroon Kannur',NULL,'Kannur',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-101'),
(102,'Aman Sha','Aman Sha',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-102'),
(103,'Ibrahim','Ibrahim',NULL,'Ponanni',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-103'),
(104,'Ansari','Ansari',NULL,'Palakkad',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-104'),
(105,'Abdulla','Abdulla Kannur',NULL,'Kannur',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-105'),
(106,'Bilal','Bilal',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-106'),
(107,'Anfus','Anfus',NULL,'Kannur',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-107'),
(108,'Anfaas','Anfaas',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-108'),
(109,'Safwan','Safwan Chilav',NULL,'Chilav',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-109'),
(110,'Mubeen','Mubeen',NULL,'Erattupeta',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-110'),
(111,'Yahya','Yahya',NULL,'TVM',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-111'),
(112,'Binyamin','Binyamin',NULL,'MUVATTUPUZHA',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-112'),
(113,'Ashfaq Rahman','Ashfaq Rahman',NULL,'Ayoor',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-113'),
(114,'Adil Rizwan','Adil Rizwan',NULL,'Palakkad',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-114'),
(115,'Adil','Adil  TVM',NULL,'TVM',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-115'),
(116,'Adil','Adil Chilav',NULL,'Chilav',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-116'),
(117,'Hashim','Hashim Parakkode',NULL,'Parakkode',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-117'),
(118,'Hashim','Hashim Koottaar',NULL,'Koottaar',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-118'),
(119,'Irfan','Irfan',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-119'),
(120,'Usman','Usman',NULL,'Kottayam',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-120'),
(121,'Faiz','Faiz Manjappetti',NULL,'Manjappetti',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-121'),
(122,'Faiz Faisal','Faiz Faisal',NULL,'Thodupuzha',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-122'),
(123,'Swalih','Swalih Aluva',NULL,'Aluva',NULL,3,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-123'),
(124,'Mahin','Mahin Chilav',NULL,'Chilav',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-124'),
(125,'Ameer','Ameer',NULL,'Kottayam',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-125'),
(126,'Safwan','Safwan Mvpt',NULL,'Muvattupuzha',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-126'),
(127,'Khaleelullah','Khaleelullah',NULL,NULL,NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-127'),
(128,'Mubarak','Mubarak Erpt',NULL,'Erattupeta',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-128'),
(129,'Zainulabidheen','Zainulabidheen',NULL,'Nedungandam',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-129'),
(130,'Moosa','Moosa',NULL,'Kanjar',NULL,2,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-130'),
(131,'Ashmil','Ashmil',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-131'),
(132,'Haris','Haris',NULL,'TVM',NULL,2,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-132'),
(133,'Afeef','Afeef',NULL,NULL,NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-133'),
(134,'Ajsel','Ajsel',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-134'),
(135,'Saeed','Saeed TDP',NULL,'Thodupuzha',NULL,1,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-135'),
(136,'Ubaidulla','Ubaidulla',NULL,'Kottarakkara',NULL,4,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-136'),
(137,'Hassan','Hassan Rajeeb',NULL,'Kottarakkara',NULL,1,1,NULL,NULL,NULL,NULL,NULL,'active','KZ-137'),
(138,'Jabir','Jabir',NULL,'Manjali',NULL,3,2,NULL,NULL,NULL,NULL,NULL,'active','KZ-138'),
(139,'Khaleelurahman','Khaleelurahman',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-139'),
(140,'Muhammed','Muhammed',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-140'),
(141,'Mubarak Ali','Mubarak Ali',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-141'),
(142,'Badusha','Badusha',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-142'),
(143,'Hudaifa','Hudaifa perumbavoor',NULL,'Perumbavoor',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-143'),
(144,'Muhsin','Muhsin Kaaralikonam',NULL,'Kaaralikonam',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-144'),
(145,'Anwar Hussain','Anwar Hussain',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-145'),
(146,'Thanzeel','Thanzeel',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-146'),
(147,'Rizwan','Rizwan Edathala',NULL,'Edathala',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-147'),
(148,'Asad','Asad Edathala',NULL,'Edathala',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-148'),
(149,'Amjad','Amjad',NULL,'Edathala',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-149'),
(150,'Aman','Aman Edathala',NULL,'Edathala',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-150'),
(151,'Ahmad Nihal','Ahmad Nihal',NULL,'Erattupetta',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-151'),
(152,'Ismail','Ismail',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-152'),
(153,'Hayath Roshan','Hayath Roshan',NULL,'Aluva',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-153'),
(154,'Raihan','Raihan',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-154'),
(155,'Ibrahim','Ibrahim',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-155'),
(156,'Misnad','Misnad',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-156'),
(157,'Sufiyan','Sufiyan',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-157'),
(158,'Naeem','Naeem',NULL,'Kanjar',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-158'),
(160,'Rabeeh','Rabeeh',NULL,'Nellikuzhi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-160'),
(161,'Hashir','Hashir',NULL,'Pallikkara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-161'),
(162,'Dilshad','Dilshad',NULL,'Todupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-162'),
(163,'Aslam U N','Aslam U N',NULL,'Thodupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-163'),
(164,'Rihan','Rihan',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-164'),
(165,'Ameen','Ameen',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-165'),
(166,'Zayan','Zayan',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-166'),
(167,'Rizwan','Rizwan Paanayikulam',NULL,'Paanayikulam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-167'),
(168,'Ilyas','Ilyas',NULL,'Nellikuzhi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-168'),
(169,'Muad','Muad perumbavoor',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-169'),
(170,'Yaseen','Yaseen PKD',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-170'),
(171,'Yoosuf','Yoosuf',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-171'),
(172,'Aman','Aman Nellikkuzhi',NULL,'Nellikkuzhi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-172'),
(173,'Hasan Muhammed','Hasan Muhammed',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-173'),
(174,'Asadullah','Asadullah',NULL,'Pattimattam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-174'),
(175,'Faiz','Faiz Vannapuram',NULL,'Vannapuram',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-175'),
(176,'Althaf','Althaf Pathanapuram',NULL,'Pathanapuram',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-176'),
(177,'Bilal','Bilal Kochi',NULL,'Kochi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-177'),
(178,'Hashim Quraishi','Hashim Quraishi',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-178'),
(179,'Mishal','Mishal',NULL,'Pandalam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-179'),
(180,'Nasrulla','Nasrulla',NULL,'Pallarimankalam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-180'),
(181,'Ansaf','Ansaf Kanjar',NULL,'Kanjar',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-181'),
(182,'Saihan','Saihan',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-182'),
(183,'Umarul Mukthar','Umarul Mukthar',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-183'),
(184,'Hisham','Hisham',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-184'),
(185,'Sayyidul Akbar','Sayyidul Akbar',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-185'),
(186,'Ishaq','Ishaq',NULL,'Kottayam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-186'),
(187,'Ihsan','Ihsan Trissur',NULL,'Trissur',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-187'),
(188,'Sayyidul Arham','Sayyidul Arham',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-188'),
(189,'Thwaha','Thwaha',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-189'),
(190,'Basil','Basil',NULL,'Thodupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-190'),
(191,'Safal','Safal',NULL,'Muvattupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-191'),
(192,'Misbahul Haque','Misbahul Haque',NULL,'Kottayam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-192'),
(193,'Muhammed O S','Muhammed O S',NULL,'Muvattupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-193'),
(194,'Abdurahman','Abdurahman',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-194'),
(195,'Nooruzaman','Nooruzaman',NULL,'Muvattupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-195'),
(196,'Ameer Ali','Ameer Ali',NULL,'Vazhakkulam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-196'),
(197,'Nihal','Nihal Ernakulam',NULL,'Ernakulam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-197'),
(198,'Umair','Umair Kasargode',NULL,'Kasargode',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-198'),
(199,'Salman','Salman Aluva','Aluva','Aluva',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-199'),
(200,'Affan','Affan Kottarakkara',NULL,'Kottarakkara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-200'),
(201,'Arif Naeem','Arif Naeem',NULL,'Vazhakkulam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-201'),
(202,'Jamsheer','Jamsheer',NULL,'Manjali',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-202'),
(203,'Umair','Umair Trissur',NULL,'Trissur',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-203'),
(205,'Zahran','Zahran',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-205'),
(206,'Salman','Salman',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-206'),
(207,'Thariq','Thariq',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-207'),
(208,'Farhan','Farhan Pattimottom',NULL,'Pattimottom',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-208'),
(209,'Ashfak','Ashfak Kombara',NULL,'Kombara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-209'),
(210,'Irshad','Irshad',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-210'),
(211,'Sa''ad','Sa''ad',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-211'),
(212,'Shabeer','Shabeer',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-212'),
(213,'Rashid','Rashid',NULL,'Thodupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-213'),
(214,'Ansari','Ansari',NULL,'Kottayam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-214'),
(215,'Minhaj','Minhaj',NULL,'Aluva',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-215'),
(216,'Bilal','Bilal Epta',NULL,'Erattupetta',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-216'),
(217,'Althaf','Althaf Kottayam',NULL,'Kottayam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-217'),
(218,'Arif Rayyan','Arif Rayyan',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-218'),
(219,'Thayyib','Thayyib',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-219'),
(220,'Abid','Abid',NULL,'Chilav',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-220'),
(221,'Hanoon','Hanoon',NULL,'Angamali',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-221'),
(222,'Thufail','Thufail',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-222'),
(223,'Abdulla','Abdulla Perumbavoor',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-223'),
(224,'Bilal','Bilal Muvattupuzha',NULL,'Muvattupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-224'),
(225,'Ihsan','Ihsan Muvattupuzha',NULL,'Muvattupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-225'),
(226,'Rilwan','Rilwan Thrissur',NULL,'Thrissur',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-226'),
(227,'Afthab','Afthab',NULL,'Thodupuzha',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-227'),
(228,'Sharaf Ali','Sharaf Ali',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-228'),
(229,'Safwan','Safwan Kottayam',NULL,'Kottayam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-229'),
(230,'Abdulla','Abdulla Kodakara',NULL,'Kodakara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-230'),
(231,'Rizwan','Rizwan Kunjattukara',NULL,'Kunjattukara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-231'),
(232,'Husama','Husama',NULL,'Kochi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-232'),
(233,'Abdulla','Abdulla Kannanthara',NULL,'Kannanthara',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-233'),
(234,'Anfal','Anfal',NULL,'Vazhakkulam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-234'),
(235,'Aslam','Aslam Palakkad',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-235'),
(236,'Abdul Hadi','Abdul Hadi',NULL,'Pattimattam',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-236'),
(237,'Bilal','Bilal Palakkad',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-237'),
(238,'Sameem','Sameem',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-238'),
(239,'Ammar','Ammar',NULL,'Nellikuzhi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-239'),
(240,'Muaaz','Muaaz Kochi',NULL,'Kochi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-240'),
(241,'Fadil','Fadil',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-241'),
(242,'Mahin','Mahin Perumbavoor',NULL,'Perumbavoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-242'),
(243,'Jasim','Jasim',NULL,'Nellikuzhi',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-243'),
(244,'Amal','Amal',NULL,'Aluva',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-244'),
(245,'Thoufeek','Thoufeek',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-245'),
(247,'Affan','Affan Aluva',NULL,'Aluva',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-247'),
(248,'Affan','Affan Paravoor',NULL,'Paravoor',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-248'),
(249,'Shameem','Shameem',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-249'),
(250,'Mahin','Mahin Edathala',NULL,'Edathala',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-250'),
(251,'Thahir','Thahir',NULL,NULL,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-251'),
(252,'Althaf','Althaf PKD',NULL,'Palakkad',NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,'active','KZ-252')
ON CONFLICT (source_id) DO UPDATE SET full_name=excluded.full_name,display_name=excluded.display_name,name_arabic=excluded.name_arabic,place=excluded.place,admission_no=excluded.admission_no,class_id=excluded.class_id,maddhab_id=excluded.maddhab_id,phone=excluded.phone,email=excluded.email,dob=excluded.dob,guardian_name=excluded.guardian_name,guardian_phone=excluded.guardian_phone,status=excluded.status,chess_number=excluded.chess_number,updated_at=now();

commit;
